[client]
toolbarMode = "minimal"

[theme]
base = "dark"
backgroundColor = "#000000"
font="JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
codeFont="JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
headingFont="JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
